export const districtsData = [
  {
    name: "Bagerhat",
    upazilas: [
      "Bagerhat Sadar",
      "Mongla",
      "Morrelganj",
      "Rampal",
      "Sarankhola",
      "Kachua",
      "Fakirhat",
    ],
  },
  {
    name: "Bandarban",
    upazilas: ["Bandarban Sadar", "Thanchi", "Ruma", "Lama", "Rowangchhari"],
  },
  {
    name: "Barguna",
    upazilas: ["Barguna Sadar", "Amtali", "Taltali", "Betagi", "Patharghata"],
  },
  {
    name: "Barishal",
    upazilas: [
      "Barishal Sadar",
      "Babuganj",
      "Bakerganj",
      "Banaripara",
      "Gournadi",
      "Hizla",
      "Mehendiganj",
      "Muladi",
      "Wazirpur",
    ],
  },
  {
    name: "Bhola",
    upazilas: [
      "Bhola Sadar",
      "Burhanuddin",
      "Char Fasson",
      "Lalmohan",
      "Manpura",
      "Tazumuddin",
    ],
  },
  {
    name: "Bogra",
    upazilas: [
      "Bogra Sadar",
      "Shibganj",
      "Sherpur",
      "Dhunat",
      "Nandigram",
      "Sariakandi",
      "Gabtali",
      "Sonatala",
      "Adamdighi",
      "Kahaloo",
    ],
  },
  {
    name: "Brahmanbaria",
    upazilas: [
      "Brahmanbaria Sadar",
      "Ashuganj",
      "Kasba",
      "Nabinagar",
      "Sarail",
      "Sarail",
      "Bancharampur",
      "Bijoynagar",
    ],
  },
  {
    name: "Chandpur",
    upazilas: [
      "Chandpur Sadar",
      "Faridganj",
      "Haimchar",
      "Kachua",
      "Shahrasti",
    ],
  },
  {
    name: "Chattogram",
    upazilas: [
      "Chattogram Sadar",
      "Pahartali",
      "Chandgaon",
      "Anwara",
      "Fatikchhari",
      "Rangunia",
      "Raozan",
      "Satkania",
      "Mirsharai",
      "Sandwip",
      "Boalkhali",
      "Hathazari",
      "Lohagara",
      "Banshkhali",
    ],
  },
  {
    name: "Chuadanga",
    upazilas: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
  },
  {
    name: "Comilla",
    upazilas: [
      "Comilla Sadar",
      "Barura",
      "Brahmanpara",
      "Burichang",
      "Chandina",
      "Chauddagram",
      "Daudkandi",
      "Debidwar",
      "Homna",
      "Meghna",
      "Monohorgonj",
      "Muradnagar",
      "Titas",
      "Comilla Adarsha Sadar",
    ],
  },
  {
    name: "Cox's Bazar",
    upazilas: [
      "Cox's Bazar Sadar",
      "Chakaria",
      "Maheshkhali",
      "Ramu",
      "Teknaf",
      "Ukhia",
      "Kutubdia",
      "Pekua",
      "Moheshkhali",
    ],
  },
  {
    name: "Dhaka",
    upazilas: [
      "Dhaka North",
      "Dhaka South",
      "Dhamrai",
      "Dohar",
      "Keraniganj",
      "Nawabganj",
      "Savar",
      "Gazipur Sadar",
      "Kaliakair",
      "Tongi",
      "Kaliakair",
    ],
  },
  {
    name: "Dinajpur",
    upazilas: [
      "Dinajpur Sadar",
      "Birampur",
      "Birganj",
      "Biral",
      "Chirirbandar",
      "Ghoraghat",
      "Hakimpur",
      "Kaharole",
      "Khansama",
      "Nawabganj",
      "Parbatipur",
      "Birampur",
    ],
  },
  {
    name: "Faridpur",
    upazilas: [
      "Faridpur Sadar",
      "Alfadanga",
      "Boalmari",
      "Madhukhali",
      "Nagarkanda",
      "Sadarpur",
      "Bhanga",
    ],
  },
  {
    name: "Feni",
    upazilas: [
      "Feni Sadar",
      "Chhagalnaiya",
      "Parshuram",
      "Daganbhuiyan",
      "Fulgazi",
      "Sonagazi",
      "Feni Adarsha Sadar",
    ],
  },
  {
    name: "Gaibandha",
    upazilas: [
      "Gaibandha Sadar",
      "Gobindaganj",
      "Palashbari",
      "Sundarganj",
      "Shaghata",
      "Sundarganj",
      "Phulchhari",
    ],
  },
  {
    name: "Gazipur",
    upazilas: ["Gazipur Sadar", "Kaliakair", "Tongi", "Kapasia", "Sreepur"],
  },
  {
    name: "Gopalganj",
    upazilas: ["Gopalganj Sadar", "Kashiani", "Muksudpur", "Tungipara"],
  },
  {
    name: "Habiganj",
    upazilas: [
      "Habiganj Sadar",
      "Ajmiriganj",
      "Bahubal",
      "Baniachong",
      "Chunarughat",
      "Lakhai",
      "Madhabpur",
      "Nabiganj",
    ],
  },
  {
    name: "Jamalpur",
    upazilas: [
      "Jamalpur Sadar",
      "Dewanganj",
      "Islampur",
      "Madarganj",
      "Melandaha",
      "Sarishabari",
      "Baksiganj",
      "Melandaha",
    ],
  },
  {
    name: "Jashore",
    upazilas: [
      "Jashore Sadar",
      "Abhaynagar",
      "Bagherpara",
      "Chowgacha",
      "Jhikargacha",
      "Keshabpur",
      "Manirampur",
      "Sharsha",
    ],
  },
  {
    name: "Jhalokathi",
    upazilas: ["Jhalokathi Sadar", "Kathalia", "Nalchity", "Rajapur"],
  },
  {
    name: "Jhenaidah",
    upazilas: [
      "Jhenaidah Sadar",
      "Kaliganj",
      "Kotchandpur",
      "Maheshpur",
      "Shailkupa",
    ],
  },
  {
    name: "Joypurhat",
    upazilas: ["Joypurhat Sadar", "Akkelpur", "Kalai", "Khetlal", "Panchbibi"],
  },
  {
    name: "Khagrachhari",
    upazilas: [
      "Khagrachhari Sadar",
      "Dighinala",
      "Lakshmichhari",
      "Mahalchhari",
      "Manikchhari",
      "Matiranga",
      "Panchhari",
      "Ramgarh",
    ],
  },
  {
    name: "Khulna",
    upazilas: [
      "Khulna Sadar",
      "Batiaghata",
      "Dumuria",
      "Dacope",
      "Paikgachha",
      "Terokhada",
      "Rupsa",
      "Koyra",
      "Dighalia",
      "Bagerhat Sadar",
    ],
  },
  {
    name: "Kishoreganj",
    upazilas: [
      "Kishoreganj Sadar",
      "Austagram",
      "Bajitpur",
      "Bhairab",
      "Hossainpur",
      "Itna",
      "Karimganj",
      "Katiadi",
      "Kuliarchar",
      "Mithamain",
      "Nikli",
      "Pakundia",
      "Tarail",
    ],
  },
  {
    name: "Kurigram",
    upazilas: [
      "Kurigram Sadar",
      "Bhurungamari",
      "Nageshwari",
      "Phulbari",
      "Rajarhat",
      "Ulipur",
      "Chilmari",
      "Char Rajibpur",
      "Rowmari",
      "Kurigram Sadar",
    ],
  },
  {
    name: "Kushtia",
    upazilas: [
      "Kushtia Sadar",
      "Bheramara",
      "Kumarkhali",
      "Mirpur",
      "Daulatpur",
    ],
  },
  {
    name: "Lakshmipur",
    upazilas: [
      "Lakshmipur Sadar",
      "Raipur",
      "Ramganj",
      "Ramgati",
      "Kamalnagar",
    ],
  },
  {
    name: "Lalmonirhat",
    upazilas: [
      "Lalmonirhat Sadar",
      "Aditmari",
      "Hatibandha",
      "Kaliganj",
      "Patgram",
    ],
  },
  {
    name: "Madaripur",
    upazilas: ["Madaripur Sadar", "Kalkini", "Rajoir", "Shibchar"],
  },
  {
    name: "Magura",
    upazilas: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  },
  {
    name: "Manikganj",
    upazilas: [
      "Manikganj Sadar",
      "Singair",
      "Saturia",
      "Shivalaya",
      "Harirampur",
      "Daulatpur",
    ],
  },
  {
    name: "Meherpur",
    upazilas: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
  },
  {
    name: "Moulvibazar",
    upazilas: [
      "Moulvibazar Sadar",
      "Barlekha",
      "Kamalganj",
      "Kulaura",
      "Rajnagar",
      "Sreemangal",
      "Moulvibazar Sadar",
    ],
  },
  {
    name: "Munshiganj",
    upazilas: [
      "Munshiganj Sadar",
      "Gazaria",
      "Lohajang",
      "Sreenagar",
      "Sirajdikhan",
    ],
  },
  {
    name: "Mymensingh",
    upazilas: [
      "Mymensingh Sadar",
      "Bhaluka",
      "Trishal",
      "Muktagachha",
      "Gaffargaon",
      "Phulpur",
      "Haluaghat",
      "Fulbaria",
      "Nandail",
      "Ishwarganj",
    ],
  },
  {
    name: "Naogaon",
    upazilas: [
      "Naogaon Sadar",
      "Atrai",
      "Badalgachhi",
      "Dhamoirhat",
      "Manda",
      "Niamatpur",
      "Patnitala",
      "Porsha",
      "Raninagar",
      "Sapahar",
    ],
  },
  {
    name: "Narail",
    upazilas: ["Narail Sadar", "Kalia", "Lohagara"],
  },
  {
    name: "Narsingdi",
    upazilas: [
      "Narsingdi Sadar",
      "Belabo",
      "Monohardi",
      "Palash",
      "Raipura",
      "Shibpur",
    ],
  },
  {
    name: "Natore",
    upazilas: ["Natore Sadar", "Baraigram", "Bagatipara", "Lalpur", "Singra"],
  },
  {
    name: "Nawabganj",
    upazilas: [
      "Nawabganj Sadar",
      "Shibganj",
      "Dhamoirhat",
      "Patnitala",
      "Badalgachhi",
    ],
  },
  {
    name: "Netrokona",
    upazilas: [
      "Netrokona Sadar",
      "Barhatta",
      "Durgapur",
      "Kalmakanda",
      "Khaliajuri",
      "Mohanganj",
      "Purbadhala",
      "Atpara",
    ],
  },
  {
    name: "Nilphamari",
    upazilas: [
      "Nilphamari Sadar",
      "Dimla",
      "Domar",
      "Jaldhaka",
      "Kishoreganj",
      "Saidpur",
    ],
  },
  {
    name: "Noakhali",
    upazilas: [
      "Noakhali Sadar",
      "Begumganj",
      "Chatkhil",
      "Companiganj",
      "Hatiya",
      "Senbagh",
      "Subarnachar",
      "Sonaimuri",
    ],
  },
  {
    name: "Pabna",
    upazilas: [
      "Pabna Sadar",
      "Bera",
      "Atgharia",
      "Bhangura",
      "Chatmohar",
      "Faridpur",
      "Ishwardi",
      "Santhia",
      "Sujanagar",
    ],
  },
  {
    name: "Panchagarh",
    upazilas: ["Panchagarh Sadar", "Debiganj", "Boda", "Tetulia"],
  },
  {
    name: "Patuakhali",
    upazilas: [
      "Patuakhali Sadar",
      "Bauphal",
      "Dashmina",
      "Galachipa",
      "Kalapara",
      "Rangabali",
      "Dumki",
      "Mirzaganj",
    ],
  },
  {
    name: "Pirojpur",
    upazilas: [
      "Pirojpur Sadar",
      "Bhandaria",
      "Kawkhali",
      "Mathbaria",
      "Nazirpur",
      "Nesarabad",
      "Indurkani",
    ],
  },
  {
    name: "Rajbari",
    upazilas: [
      "Rajbari Sadar",
      "Baliakandi",
      "Goalandaghat",
      "Pangsha",
      "Kalukhali",
    ],
  },
  {
    name: "Rajshahi",
    upazilas: [
      "Rajshahi Sadar",
      "Bagha",
      "Bagmara",
      "Charghat",
      "Durgapur",
      "Godagari",
      "Mohanpur",
      "Paba",
      "Puthia",
      "Tanore",
    ],
  },
  {
    name: "Rangamati",
    upazilas: [
      "Rangamati Sadar",
      "Kaptai",
      "Rajasthali",
      "Belaichhari",
      "Kaukhali",
      "Bagaichhari",
      "Juraichhari",
    ],
  },
  {
    name: "Rangpur",
    upazilas: [
      "Rangpur Sadar",
      "Badarganj",
      "Gangachhara",
      "Kaunia",
      "Mithapukur",
      "Pirganj",
      "Pirgachha",
      "Pirganj",
      "Taraganj",
    ],
  },
  {
    name: "Satkhira",
    upazilas: [
      "Satkhira Sadar",
      "Kalaroa",
      "Debhata",
      "Assasuni",
      "Tala",
      "Shyamnagar",
      "Kaliganj",
    ],
  },
  {
    name: "Shariatpur",
    upazilas: [
      "Shariatpur Sadar",
      "Bhedarganj",
      "Gosairhat",
      "Naria",
      "Damudya",
      "Zajira",
    ],
  },
  {
    name: "Sherpur",
    upazilas: [
      "Sherpur Sadar",
      "Nakla",
      "Nalitabari",
      "Sreebardi",
      "Jhenaigati",
    ],
  },
  {
    name: "Sirajganj",
    upazilas: [
      "Sirajganj Sadar",
      "Belkuchi",
      "Chauhali",
      "Raiganj",
      "Shahjadpur",
      "Tarash",
      "Ullahpara",
      "Kamarkhanda",
    ],
  },
  {
    name: "Sunamganj",
    upazilas: [
      "Sunamganj Sadar",
      "Bishwamvarpur",
      "Chhatak",
      "Derai",
      "Dharmapasha",
      "Dowarabazar",
      "Jagannathpur",
      "Jaintiapur",
      "Sullah",
      "Tahirpur",
    ],
  },
  {
    name: "Sylhet",
    upazilas: [
      "Sylhet Sadar",
      "Beanibazar",
      "Bishwanath",
      "Companiganj",
      "Fenchuganj",
      "Gowainghat",
      "Golapganj",
      "Jaintiapur",
      "Kanaighat",
      "Osmaninagar",
      "Zakiganj",
    ],
  },
  {
    name: "Tangail",
    upazilas: [
      "Tangail Sadar",
      "Bhuapur",
      "Delduar",
      "Dhanbari",
      "Gopalpur",
      "Kalihati",
      "Madhupur",
      "Mirzapur",
      "Nagarpur",
      "Sakhipur",
    ],
  },
  {
    name: "Thakurgaon",
    upazilas: ["Thakurgaon Sadar", "Pirganj", "Ranisankail", "Haripur"],
  },
];
